data=dlmread('compare_4.txt');


p_1 = data(data(:,1)==1,:);
p_2 = data(data(:,1)==2,:);
p_4 = data(data(:,1)==4,:);


sizes = ([7,8,9,10,11,12,13,14,15,16,17,18].^3)*23;

x=[];
dlpoly1=[];
ppmd1=[];

dlpoly2=[];
ppmd2=[];


dlpoly4=[];
ppmd4=[];



for s = sizes
    x=[x,s];
    sdata = p_1(p_1(:,2)==s,3:5);
    
    p=polyfit(sdata(:,1),sdata(:,2),1)./s;
    dlpoly1=[dlpoly1, p(1)];
    
    p=polyfit(sdata(:,1),sdata(:,3),1)./s;
    
    ppmd1=[ppmd1, p(1)];
    

end



for s = sizes
    
    sdata = p_2(p_2(:,2)==s,3:5);
    
    p=polyfit(sdata(:,1),sdata(:,2),1)./s;
    dlpoly2=[dlpoly2, p(1)];
    
    p=polyfit(sdata(:,1),sdata(:,3),1)./s;
    
    ppmd2=[ppmd2, p(1)];
    

end

for s = sizes
    
    sdata = p_4(p_4(:,2)==s,3:5);
    
    p=polyfit(sdata(:,1),sdata(:,2),1)./s;
    dlpoly4=[dlpoly4, p(1)];
    
    p=polyfit(sdata(:,1),sdata(:,3),1)./s;
    
    ppmd4=[ppmd4, p(1)];
    

end



figure(1)
clf

plot(x,1000000*dlpoly1, '-r','LineWidth', 2)
hold on
plot(x,1000000*ppmd1,'--r', 'LineWidth', 2)
plot(x,1000000*dlpoly2,'color', [0,0.7,0], 'LineWidth', 2)
plot(x,1000000*ppmd2,'--','color', [0,0.7,0], 'LineWidth', 2)
plot(x,1000000*dlpoly4,'-b', 'LineWidth', 2)
plot(x,1000000*ppmd4,'--b', 'LineWidth', 2);

%t = title({'Time per particle per iteration, DL\_POLY solid lines,';' autogenerated code dashed lines.'}, 'FontSize',16);
xlabel('Number of particles', 'FontSize',16)
ylabel('Time per particle per iteration (\mus)', 'FontSize',16)


AX=legend('1 proc DL\_POLY4','1 proc autogenerated code','2 proc DL\_POLY4','2 proc autogenerated code','4 proc DL\_POLY4','4 proc autogenerated code');
LEG = findobj(AX,'type','text');

set(LEG,'FontSize',16)
set(gca,'FontSize',16)

P0 = get(AX,'Position');
set(AX, 'Position', [P0(1)+0.05 P0(2)+0.1 P0(3) P0(4)])

%P = get(t,'Position');

%set(t,'Position',[P(1)-20000 P(2) P(3)]);

axis([0,14*(10^4),0,3])

disp('ppmd')

ppmd1(11)/ppmd2(11)
ppmd1(11)/ppmd4(11)

dlpoly1(11)/dlpoly2(11)
dlpoly1(11)/dlpoly4(11)




















